### ISSUE TITLE
Nginx stop working after update apache or whm ?

### ISSUE THREAD

**Issue by petarkozic** [engintron/engintron#383]
Does someone know why Nginx stop working and don't respond after apache update or WHM update.

Every time when apache or whm update, nginx stop responding and all sites goes down.

After restarting Nginx everything works very well.

Thanks.

**Comment by DaRkRaGe** [comment]
Happens to me all the time

**Comment by petarkozic** [comment]
Yes, that's is huge problem. I have 4 production server with few hundreds users.
Every time when apache update, monitoring alerting nginx status.

After restarting nginx services everithing works fine.
I expect some solutions for this problem, especially because engintron is now registered whm services.

**Comment by jcals** [comment]
Same here, in my case, both webservers work, but I get 502 and 503 errors :(

**Comment by fevangelou** [comment]
Version 1.8.1 will add a service check for Nginx in cPanel's monitoring, so that should be resolved.

**Comment by petarkozic** [comment]
This problem is not resolved !
After updating Apache Nginx need usually 7-8 minutes to restart Nginx. That is much downtime for servers where I have more then 1000 accounts !

**Comment by fevangelou** [comment]
Why would Nginx need 7-8 mins to restart? I recently did performance optimizations on 2 such servers and reload or restarting Nginx was instant. Your bottleneck is elsewhere.
