### ISSUE TITLE
After installing I get 500 Internal Server Error

### ISSUE THREAD

**Issue by MarkWest2017** [engintron/engintron#412]
Hi,
After installing Engintron I am now getting 500 errors on all my sites.
Both the nginx status and apache status report they are up and nginx -t reports all ok, so I'm confused.
I have nginx running on ports 80 & 443 and apache running on 8080 and 8443 - but when I look at the apache status in cPanel I only see connections for port 8080 - like it's not listening on 8443?
Hope you can help.
Thanks
Mark

**Comment by MarkWest2017** [comment]
Hi,
A quick update.  In the nginx logs I am seeing this error repeated -(111: Connection refused)
It seems like connections to HTTPS are being redirected to HTTP somehow?  Or the HTTPS request is being ignored maybe?
Hope you can help me get this sorted out.
Thanks
Mark

**Comment by tinycg** [comment]
Just installed and am seeing 502 bad gateway errors and the same 111 connection refused in the error logs.

**Comment by fevangelou** [comment]
Apache seems to get stuck for some reason and can't get restart. Either restart Apache from WHM (via Home » Restart Services »HTTP Server (Apache)) or simply upgrade Engintron once more (to today's build) which does the above automatically on update.

Let me know.

**Comment by MarkWest2017** [comment]
Hi Fotis,

Thank you for your response.

I've just updated through WHM to nginx stable (via Enginetron 
interface), this is the chunk of the log that I think is relevant -

---

=== Switch Apache to ports 8080 & 8443, distill changes & restart Apache ===
---
metadata:
   command: set_tweaksetting
   reason: OK
   result: 1
   version: 1
---
metadata:
   command: set_tweaksetting
   reason: OK
   result: 1
   version: 1


=== Distill changes in Apache's configuration and restart Apache ===
Built /etc/apache2/conf/httpd.conf OK
Waiting for “httpd” to start ……………failed.

Service Error
     (XID yrmmmk) The “httpd” service failed to start.

Startup Log
     (98)Address already in use: AH00072: make_sock: could not bind to 
address [::]:8080
     (98)Address already in use: AH00072: make_sock: could not bind to 
address 0.0.0.0:8080
     no listening sockets available, shutting down
     AH00015: Unable to open logs
---


Maybe you can shed some light on why this might be.  I tested yesterday 
by disabling Engintron and I was still getting the 500 error with just 
apache?

Thanks very much

Mark

**Comment by tux-tn** [comment]
Another service is listening on port 8080 (This can explain why apache can't start)

You can find out which one by connecting in ssh and typing this command `netstat -lntp | grep 8080` 
netstat lists the listening ports and associated services and grep will show you only which one is listening on port 8080

**Comment by MarkWest2017** [comment]
Hi,

Thank you for your help so far.  I fixed an underlying Apache issue - so that is now working.

But, when I enable Engintron my sites top working and I see these errors -

2017/02/23 06:10:35 [error] 1453#1453: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.0", upstream: "http://127.0.0.1:8080/"

I'd be grateful if you could let me know what to check next?

Thanks

Mark

**Comment by tux-tn** [comment]
Nginx is unable to connect to Apache on port 8080. 
You still have issues with Apache, i guess you should recheck if Apache is listening on port 8080

**Comment by highacid** [comment]
@tux-tn I have the same issues here, with 502 on partial sites. So this does not make any sense, 10 sites work just fine, and another 15 do not work and throw 502. I had 2 previous threads on this issue, since it is not new, I jumped across it few months ago, and since then of course nothing or no one had a working solution it seems, since people are hitting this issues too. By the way, my issue is still not solved, the only way to serve customers is to do it with Apache only at the moment.

**Comment by fevangelou** [comment]
@all Upgrade to today's build. The problem is automatically resolved by restarting Apache after the installation. This is why Nginx cannot connect to Apache at all.

**Comment by amirvenus** [comment]
Guys, make sure your files and folders have the right permission. I figured that out after trying everything else!
