### ISSUE TITLE
https

### ISSUE THREAD

**Issue by gemisu** [engintron/engintron#431]
We have upgraded to version 1.8.0 but client sites browsing through https do not open. any ideas?

**Comment by Cavain** [comment]
@gemisu i got that same issue on my server, Solution is after upgrading to 1.8.0 purge all cache files and disable Engintron and then enable it. Then it will start working. I hope it will works for you.
Have a great day!

**Comment by ubidzz** [comment]
Make sure that PHP open_basedir Protection is turned off and then restart the nginx server and the cronjob will automatically fix your default_https.conf file.

**Comment by Nirjonadda** [comment]
@ubidzz What problem happen with Enable php open_basedir Protection? I see we have Enabled php open_basedir Protection but does not seen any error.

http://image.prntscr.com/image/190268b5c06b48218fce16dcbce20c0a.png

**Comment by ubidzz** [comment]
@Nirjonadda if php open_basedir protection is enabled it will provent Engintron from getting the info from the httpd.conf file and creating the the nginx default_http.conf file you must turn the php open_basedir Protection off so that nginx server can get your vhost info and put it in to it conf file. The php open_basedir protection will have to stay turned off because it runs every 1 minute and if it's turned back on it will brake your SSL websites.

I know you may not like having the php open_basedir protection turned off but it the only way the nginx server can get your installed cPanel SSL info. because @fevangelou made the file using PHP scripting to get the info from the httpd.conf file and should of did it by a bash script instead so that we don't have to turn off the open_basedir protection. I seen a lot of comments due to this problem and it not stated in his readme file to turn the open_basedir protection off. I did make a bash script to do what he doing and told him but this is @fevangelou plugin so it is totally up to him how he want to build this plugin and can only hope he fix this problem.

**Comment by mgmaik** [comment]
I turned open_basedir off but still have the SSL cert error

**Comment by ubidzz** [comment]
click the **Purge cache & temp files** and then click the **Restart** in the WHM Engintron plugin. If the pages still don't work give it a few minutes to have the cronjob build the default_https.conf file for your nginx server.

**Comment by Nirjonadda** [comment]
@ubidzz OK, I have Disabled open_basedir protection but @fevangelou are not added any info via Engintron wiki page about need to disable open_basedir protection.

**Comment by mgmaik** [comment]
I've purged cache & temp files and restarted engintron but still nothing. I've waited half an hour for the cronjob. 

When I _disable_ engintron all my ssl sites works perfectly without cert errors.
certs are from whm autossl by letsencrypt

**Comment by Nirjonadda** [comment]
@mgmaik Please can you try to use AutoSSL Providers cPanel (powered by Comodo)? If this work.

**Comment by ubidzz** [comment]
Do you have CSF installed if so look in the logs for the cronjob and see if it is running this command 
`(root) CMD (/etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1)` 
Also check the Apache SSL port if it is 0.0.0.0:8443 in the Server Configuration »Tweak Settings » System page.
Also check the Nginx error log to see if there is any errors in that.

I use AutoSSL and have no issues with it.

@Nirjonadda He did add it in the wiki but you have to find it under the Requirements and should be stated in the readme file under the install commands.
https://github.com/engintron/engintron/wiki/Requirements

**Comment by Nirjonadda** [comment]
> open_basedir protection is disabled in your system. If you're using the right build mode for PHP (aka you DON'T use mod_**# dso**)

@ubidzz What PHP Handlers you are using? I am still using DSO but other PHP Handlers not work with Zend OPcache.

**Comment by mgmaik** [comment]
I can see in CSF that the cron is running. I've also check the Apache SSL port with is 0.0.0.0:8443.
I don't see any thing wrong in the Nginx error logo too.

I've made screenshots of the error when I turn Engintron off and on
![screen shot 2017-02-24 at 1 14 18 pm](https://cloud.githubusercontent.com/assets/22024546/23303240/389762ca-fa93-11e6-9342-fe5aab73d7d5.png)
![screen shot 2017-02-24 at 1 13 44 pm](https://cloud.githubusercontent.com/assets/22024546/23303241/38ac2f70-fa93-11e6-9ee0-9583d31c850d.png)

**Comment by ubidzz** [comment]
@Nirjonadda 
```
/usr/local/cpanel/bin/rebuild_phpconf --current
DEFAULT PHP: ea-php56
ea-php54 SAPI: cgi
ea-php55 SAPI: cgi
ea-php56 SAPI: cgi
ea-php70 SAPI: cgi
ea-php71 SAPI: cgi
```

@mgmaik i went to your website that is shown in your screenshots and the page load for me.

**Comment by Nirjonadda** [comment]
@ubidzz PHP handler CGI is work with cache? Like: OPcache, Redis, APCu

Do you have any experience or recommendation to using FCGI PHP handler?

**Comment by ubidzz** [comment]
@Nirjonadda I have no issues with my PHP

Here is what i have turned on
Apache MPM
|──mod_mpm_prefork
Apache Modules
|──mod_cgi
|──mod_unique_id
|──mod_ssl
|──mod_security2
|──mod_ruid2
|──mod_remoteip
|──mod_proxy_http
|──mod_proxy
|──mod_mpm_prefork
|──mod_headers
|──mod_expires
|──mod_deflate
PHP Versions
|──php54
|──php55
|──php56
|──php70
|──php71
PHP Extensions
|──List is way to long to post here but pretty much almost all of them are turned on

Hope that helps you.

**Comment by mgmaik** [comment]
@ubidzz I turned Engintron off.. My clients will freak out

**Comment by ubidzz** [comment]
It looks like you can run them but will turn off other things if they are turned on here is a example for opcache.

The following conflicts are installed on this machine. They will be removed as part of this package selection:
php55-php-zendguard
The following requirements are not installed on this machine. They will be added as part of this package selection:
php55-php-opcache

All you can do is tray it and see if it works because using nginx is worth it instead of only the apache server.

**Comment by Nirjonadda** [comment]
PHP handler CGI is now enabled.

**Comment by gemisu** [comment]
I still can not navigate through https.
Does anyone know how to solve it?

**Comment by ubidzz** [comment]
@gemisu i have the same output as you and make sure that open_basedir protection is disabled. Other then that the only thing i can think of is that your server not configured correctly and you can see what php stuff i use in the comments above.

**Comment by ubidzz** [comment]
@gemisu check this file
nano /etc/nginx/conf.d/default_https.conf
and see if your domains are listed in it with the SSL stuff.

**Comment by gemisu** [comment]
default_https.conf   ????

That never has been

**Comment by ubidzz** [comment]
If you are missing the default_https.conf file then Engintron is not building that file because of a issue with your server. Check the /etc/nginx/utilities/ folder to see if you see a file named error_log and it will give you the error in it. and try to run this /etc/nginx/utilities/https_vhosts.sh it will try to build that file for you and may take a few minutes to fully run.

**Comment by gemisu** [comment]
Run the script and rebuild the file.
Clean logs, turn the engintron off and on and everything is fine now if I log in by https :)

Thank you so much

**Comment by ubidzz** [comment]
There is a cronjob that should of ran that builds the default_https.conf file and checks the httpd file automatically and you will have to make sure it is in your cronjob file at `nano /etc/crontab` and make sure that this line is in it.
`* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1`

**Comment by gemisu** [comment]
My crontab file was empty and I put it

Thank you

**Comment by ubidzz** [comment]
That not good there should of been another command in it.

`SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs
# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed

*/1 * * * * root /usr/local/rtm/bin/rtm 48 > /dev/null 2> /dev/null

* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1`

I am pretty sure this is cPanel default crontab file with nginx added to it and make sure the permissions are `-rw-r--r--. 1 root root` by running `ls -l /etc/crontab` if the permissions is not correct then change them with `chmod 0644 /etc/crontab`

**Comment by gemisu** [comment]
Centos 7 whith whm/cpanel 62.0.16 - cloudlinux 7.3 :)

**Comment by fevangelou** [comment]
Actually this is all you need:

```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed

* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1
```

@ubidzz 's crontab has an additional line which is not needed.

Edit your crontab file from within Engintron's WHM app. It will restart the crond service as well.

**Comment by ubidzz** [comment]
@fevangelou last time i try to use Engintron's to edit the crontab file it end up braking it by adding hidden `^M` on every line and i had to delete crontab file and recreate it.

**Comment by bernieddevil** [comment]
Since upgrading to 1.8 all non-http sites stopped working so disabled Engintron. Today noticed a new update to 1.8.2 and after running this update all non-http sites working again with nice speed boost so thanks to developer for fixing the issue.

**Comment by ahlul** [comment]
Another tweak for Centos 7:

I found service nginx reload in vhost https script not work on centos 7. I've test it when update SSL, vhost file updated, but nginx not reload it config.

So i change it: service nginx reload on /etc/nginx/utilities/https_vhosts.sh to nginx -s reload
And it work again..

**Comment by fevangelou** [comment]
@ubidzz It was fixed in 1.8.1. The editor was adding Windows line endings causing issues.
@bernieddevil Cool!
@ahlul "service nginx reload" should redirect to the systemd related command either way. How do you know it's not working? Did you execute "service nginx reload" in a terminal with no output?

**Comment by ahlul** [comment]
@fevangelou Yes, no output.. I've check multiple times..

Nginx config not reload using service nginx reload on Centos 7, have some server with Centos 7, same results. So my conclution, service nginx reload not work on Centos 7

Then I changed it with "nginx -s reload" and it works :)

**Comment by fevangelou** [comment]
@ahlul Well, it should work. One last question. Do this do anything on your server?
```
systemctl reload nginx.service
```

**Comment by gemisu** [comment]
@fevangelou My server does not create the file

/etc/nginx/conf.d/default_https.conf

And file /etc/crontab Leave it blank.

I always have to copy the one I had backed up and add the ngnix line

And then I execute the

/etc/nginx/utilities/https_vhosts.sh

And finally I turn off and on the engintron

And all normal :(

**Comment by ahlul** [comment]
@fevangelou 

:D sorry I think that my fault, "service nginx reload" is works.. but when i run it directly on console.
https vhost generated, but nginx not reload, that why I think it not work previously...

Another problem that I got is, when SSL is removed from cpanel, https vhost is changed but when I access https:// on that domain (with SSL removed) it load another website  (first SSL virtualhost on apache). Nginx reload not work, even manually. So, I try to restart nginx, and it works..
May be it related to SSL config on nginx?

BTW instead using cron I think it better using cpanel hooks :D I hope i can help write the hook, and if works i'll share it here...

**Comment by TONTRI-TECH** [comment]
Hello,

I have the same kind of issue but bit weird. PHP open_basedir Protection is turned off for all domains in my cPanel but for only 1 cpanel account and domain name Engintron not generating data within **default_https.conf**.  While for other domains it's generating and working fine. CRON is running fine and crontab file has the exact contents.  I have tried generating hosts manually executing the command but it's giving me the same result.

I am running CentOS 7 latest production and cPanel&WHM 62.0 (build 16).

Please help me. Thanks.

**Comment by TONTRI-TECH** [comment]
Also, it's generating data for an account that does not have SSL installed :O :(

**Comment by 8BallBomBom** [comment]
Also having this issue since upgrading.
Seems anything mentioned here doesn't seem to fix the issue.
Only thing that has worked is disabling engintron.
When engintron is enabled, all https sites seem to use the servers main certificate only.

Also using CentOS 7, cPanel/WHM 62.0.16, CloudLinux 7.3

**Comment by Tntdruid** [comment]
Same problem here:

When engintron is enabled, all https sites use the servers main certificate.

**Comment by Cronus89** [comment]
There is something in engintron that if a VirtualHost has an IPv6 Address and not just an IPv4, it does not build the nginx host in default_https.conf

**Comment by fevangelou** [comment]
@Cronus89 Please update to the Engintron build I just pushed. Simply update Engintron from the Engintron WHM app.

**Comment by Cronus89** [comment]
@fevangelou still not working.
I updated eningtron, build shows right at the top by the logo.
Disabled & Enabled it multiple times.
Cleared cache and logs etc.
rm'd and regenerated https config multiple times.

Still same websites, same ones with ipv6 missing.

**Comment by fevangelou** [comment]
@Cronus89 Can you please email me your httpd.conf file or just an IPv6 block that is not being generated to engintron at gmail dot com?

**Comment by Cronus89** [comment]
@fevangelou Email sent

**Comment by fevangelou** [comment]
Thanks :) Can you update to the build I just pushed? The number is the same but things should work. The regex to match multiple IPs in IPv4 & IPv6 format was not properly catching all instances.

**Comment by Cronus89** [comment]
That seems to have done it. Thanks!

**Comment by fevangelou** [comment]
Great!

I recommend @tonmoy-ajize & @8BallBomBom also upgrade to today's build to resolve these IPv6 related issues.

**Comment by Tntdruid** [comment]
Now all sites report 500 server error

**Comment by fevangelou** [comment]
@Tntdruid Clean Nginx's cache just in case and restart Apache/Nginx.

**Comment by Tntdruid** [comment]
@fevangelou 
It was  Memory Usage Restriction in apache there did the 500 error, had it there for years whit no problems.

It works now :)

**Comment by fevangelou** [comment]
@Tntdruid Great :)

**Comment by 8BallBomBom** [comment]
@fevangelou All working as expected now, thanks for the quick fix, sent some euros your way :)

**Comment by WilliamIsted** [comment]
All domains are now being served the correct SSL cert via nginx rather than the shared SSL cert. Thanks for the fix.

**Comment by fevangelou** [comment]
Great! Seems to have resolved the issue, so closing for now.

**Comment by lupetalo** [comment]
I am on v 1.8.4 and for SSL enabled sites nginx is serving server certificate. Tried tuning etc/nginx/utilities/https_vhosts.sh, it completes but with no change. Tried restarting reloading reissuing certs. Nothing makes SSL loading correctly. Please advise... I am on EA4 with CloudLinux.

**Comment by lupetalo** [comment]
update: https_vhosts.php seems to not generate new certificates at all. and it also generates errors for certs that were deleted from cPanel....
