### ISSUE TITLE
Apache Logging wrong Visitor IP

### ISSUE THREAD

**Issue by ghost** [engintron/engintron#489]
EDIT: Cleaned up threads/comments, sorry

Fresh install of Engintron on multiple EA4 cPanel servers, and noticed that Apache's logging provides the wrong client IP address - instead always logging the server IP address. It seems this is because the 'LogFormat' is not correctly updated in the Apache httpd.conf file.

To fix this, I simply edited the httpd.conf file and in the "LogFormat" section replaced the %h variable with %{X-Real-IP}i instead. Apache then began logging the correct IP address in the file.

I notice that engintron.sh currently uses the 'sed' command to update the 'LogFormat' line in the httpd.conf file after installation by adding the %a field after the %h field. Unfortunately this update does not correct the IP address problem, nor is this change made permanent because of the way cPanel rebuilds the httpd.conf file regularly.

To resolve the problem, on EA4 I needed to edit the following file as per cPanel's recommendations (https://forums.cpanel.net/threads/apache-log-format-issue-with-easyapache-4.572541/) 

```/var/cpanel/templates/apache2_4/ea4_main.default```

Note that this file provides LogFormat lines for both piped logging and non-piped logging. Both of these need to be updated to reflect the new IP address. Older servers likely do not have piped logging enabled, but I believe this is a default setting for cPanel going forward. Changing this file directly ensures that future rebuilds maintain the correct LogFormat line even if cPanel performs a rebuildhttpdconf.

**Comment by rflack1717** [comment]
Not sure how to generate a pull request, but I knocked up the following code which seems to fix the problem for ea4 installations:

`if grep -q "log_config_module" "/etc/apache2/conf/httpd.conf"; then
        # Piped logging is disabled:
        sed -i "s:LogFormat \"%h:LogFormat \"%{X-Real-IP}i:" /etc/apache2/conf/httpd.conf
elif grep -q "mod_log_config" "/etc/apache2/conf/httpd.conf"; then
        # Piped logging is enabled:
        sed -i "s:LogFormat \"%v\:%p %h:LogFormat \"%v\:%p %{X-Real-IP}i:" /etc/apache2/conf/httpd.conf
fi
`

**Comment by rflack1717** [comment]
Just to update this, unfortunately replacing the format in the httpd.conf file directly does not appear to "hold". This is typically because cPanel regenerates the httpd.conf each time a new domain is added, etc.

In the past you used to be able to use the apache distiller --update method to retain changes, but this no longer works with EasyApache 4. The more permanent workaround is to edit the following file

```/var/cpanel/templates/apache2_4/ea4_main.default```

This will allow you to change the logging format and will retain the settings between rebuilds, etc.

**Comment by meteoadriatic** [comment]
Hello, for me even this does not resolve problem. I tried every fix ever written here but nothing worked. In apache domlogs, only server IP is logged instead of visitor IP.
I'm on Cpanel 62, EA4, Engintron 1.8.2, Centos 6.

**Comment by rflack1717** [comment]
Works 100% fine for me on multiple servers. Are you sure you implemented it correctly? After editing the file you need to rebuild the httpd.conf.

**Comment by meteoadriatic** [comment]
Hello, thank you, but of course, I did /scripts/rebuildhttpdconf then service httpd restart but result is the same. So, inside /var/cpanel/templates/apache2_4/ea4_main.default I did change like this:

<IfModule mod_log_config.c>
    LogFormat "%v:%p %{X-Real-IP}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
    <IfModule logio_module>
        LogFormat "%v %{%s}t %I .\n%v %{%s}t %O ." bytesvhost
    </IfModule>
    LogFormat "%v:%p %{X-Real-IP}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%v:%p %{X-Real-IP}i %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent

On all instances of %h I replaced it with %{X-Real-IP}i

Is that good?

**Comment by rflack1717** [comment]
Did you replace it in all 5 places? Did you then restart Apache after rebuilding? Have you checked that nginx remote IP forwarding is working (Engintron - "Restore Nginx IP forwarding in Apache")?

**Comment by meteoadriatic** [comment]
On 5 places - Yes! Rebuilded Apache - Yes. Restarted Apache - Yes. Engintron - "Restore Nginx IP forwarding in Apache" - Yes (zilloin times before, again now - Yes). Result the same :(

I don't know how to check if nginx remote IP forwarding actually sends visitor IP or not. I do not see any errors after pefrorming this restoring operation from Engintron interface in output which looks OK:

`Restore Nginx IP forwarding in Apache...
======================================= === Restore IP Forwarding in Apache === ======================================= === Installing mod_remoteip for Apache === Loaded plugins: fastestmirror, universal-hooks Setting up Install Process Loading mirror speeds from cached hostfile * EA4: 85.13.201.2 * base: ftp.hosteurope.de * epel: mirrors.nic.cz * extras: mirror.daniel-jost.net * updates: centos.mirrors.psw.services Package ea-apache24-mod_remoteip-2.4.25-7.7.1.cpanel.x86_64 already installed and latest version Nothing to do Waiting for “httpd” to restart gracefully …waiting for “httpd” to initialize ………finished. Service Status httpd (/usr/sbin/httpd) is running as root with PID 17438 (pidfile check method). Log Messages [Thu Mar 23 18:11:21.559562 2017] [mpm_prefork:notice] [pid 17438] AH00163: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations [Thu Mar 23 18:10:14.988698 2017] [mpm_prefork:notice] [pid 17438] AH00163: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations [Thu Mar 23 18:10:14.615064 2017] [:notice] [pid 17391] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured. httpd restarted successfully. Reloading nginx: [ OK ] Operation completed.`

Any idea?

**Comment by rflack1717** [comment]
Are you using Apache piped logs or not?

**Comment by meteoadriatic** [comment]
Yes. Should I try with turning that off?

**Comment by rflack1717** [comment]
No, it should work fine with piped logs. Check your /etc/apache2/conf/httpd.conf file - what is LogFormat set to?

**Comment by meteoadriatic** [comment]
We are moving now in right direction :)

It was with %h but I replaced (3 places) with %{X-Real-IP}i, restarted httpd, and now it does work! But, will it be reverted on %h after something updates?

**Comment by rflack1717** [comment]
Yes, it will revert next time the conf is rebuilt. You need to edit the /var/cpanel/templates/apache2_4/ea4_main.default file and then rebuild, and the conf will update correctly.

Check if you have any other ea4_main.* files that it may be reading instead of the .default file.

**Comment by meteoadriatic** [comment]
There was .default file with %{X-Real-IP}i entries. But also .local with %h. I can guess that was the cause why %h was pulled into working conf file? So I changed also in .local (3 places). I hope this is end of troubles. Finally! Thank you very much, great help!

**Comment by rflack1717** [comment]
Yes that's right, if you have a .local file you should make the changes in there and not the .default file. I didn't have a .local file on my installations, so just changing the .default file was enough :)

If you've updated the .local file, just run a /scripts/rebuildhttpdconf and check the 'LogFormat' in /etc/apache2/conf/httpd.conf - if you see the X-Real-IP field, it's working fine.

**Comment by meteoadriatic** [comment]
Works fine! Thank you again! I hope someone else can also benefit from this post.

**Comment by rflack1717** [comment]
Great! Glad it's working for you! 😃

**Comment by Friends4U** [comment]
Will this be fixed in an update? Because it's to complex for me to change and I have the same problems, also with modsecurity tools, the ip of the server get's logged the one time and the real ip the other time...

**Comment by theoxgr** [comment]
Hello guys! i am having the same issue. Fresh new VPS with CENTOS 7.3 x86_64 kvm.

I installed Engintron, it works like a charm but i dont see visitor's real ip. I tried all solutions but none worked. Please help

**Comment by HostChefs** [comment]
Still no luck...
Does it have any relevance that both mod_cloudflare and mod_remoteip are enabled @fevangelou?

**Comment by theoxgr** [comment]
does the latest update adress the visitor ip issue?

**Comment by fevangelou** [comment]
@theoxgr & @HostChefs Tried the solution mentioned above?

**Comment by HostChefs** [comment]
@fevangelou Yes... It doesn't work! I have tried almost everything :(

P.S: Check facebook!

**Comment by fevangelou** [comment]
@HostChefs Try the following...

a) Re-install Engintron
b) Edit your httpf.conf file:
If you Apache config file is: /usr/local/apache/conf/httpd.conf
`sed -i "s:LogFormat \"%h %a:LogFormat \"%a:" /usr/local/apache/conf/httpd.conf`
If you Apache config file is: /etc/apache2/conf/httpd.conf
`sed -i "s:LogFormat \"%h %a:LogFormat \"%a:" /etc/apache2/conf/httpd.conf`

Restart Apache and Nginx and check your log files.

**Comment by Friends4U** [comment]
I have the file on both locations, how do I know which one is really used by Apache?
Or do I need to edit both?

**Comment by theoxgr** [comment]
@fevangelou i have tried your solution and all other possible solutions mentioned in this thread but nothing worked. please i need help.

**Comment by theoxgr** [comment]
can anyone help me with this? i will pay someone i just need the real ip on apache.

**Comment by theoxgr** [comment]
i give up. i uninstalled enginetron. many clients had issues with their SSL's and also i had wrong visitor IP in the firewall. sorry but i cant wait forever for support.

**Comment by fevangelou** [comment]
@Friends4U The check seems fine on my end.
@theoxgr Engintron is open source which means it does take some digging around on your own. If things didn't work for you, perhaps your Apache configuration/environment was modified in such a way that it's impossible for me (or anyone else) to suggest solutions.

**Comment by faca5** [comment]
Hello.

It works but once Apache updated then it need be replaced again. Do you have better solution?

**Comment by ahmedelfaleh** [comment]
It works with me when replace %h with %{X-Real-IP}i

**Comment by fevangelou** [comment]
There is also this: https://engintron.com/docs/#/pages/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel

**Comment by ahmedelfaleh** [comment]
Actually I am applying your solution on all of my servers, only one server accepted the one mentioned above.

**Comment by ahmedelfaleh** [comment]
Guys, I just need some clarification, why in some cases %{X-Real-IP}i works instead of %a?

**Comment by fevangelou** [comment]
Using %a is better.

**Comment by ahmedelfaleh** [comment]
Guys, I just need some clarification, why in some cases %{X-Real-IP}i works instead of %a?

@fevangelou 
Can you tell me how to active %a instead of %{X-Real-IP}i and what may prevent %a to work with me?
